package de.hdm.getThePoint.db.dbmodel;

// Generated 30.12.2014 21:24:32 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Antwort generated by hbm2java
 */
@Entity
@Table(name = "Antwort", catalog = "getthepointdb")
public class Antwort extends HibernateModel {

	private static final long serialVersionUID = 4532428067635261546L;
	private int id;
	private Frage frage;
	private String text;
	private Set<Frage> frages = new HashSet<Frage>(0);
	private Set<Ergebnis> ergebnises = new HashSet<Ergebnis>(0);

	public Antwort() {
	}

	public Antwort(int id) {
		this.id = id;
	}

	public Antwort(int id, Frage frage, String text, Set<Frage> frages,
			Set<Ergebnis> ergebnises) {
		this.id = id;
		this.frage = frage;
		this.text = text;
		this.frages = frages;
		this.ergebnises = ergebnises;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "frage_id")
	public Frage getFrage() {
		return this.frage;
	}

	public void setFrage(Frage frage) {
		this.frage = frage;
	}

	@Column(name = "text", length = 45)
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "antwort")
	public Set<Frage> getFrages() {
		return this.frages;
	}

	public void setFrages(Set<Frage> frages) {
		this.frages = frages;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "antwort")
	public Set<Ergebnis> getErgebnises() {
		return this.ergebnises;
	}

	public void setErgebnises(Set<Ergebnis> ergebnises) {
		this.ergebnises = ergebnises;
	}

}
