package de.hdm.getThePoint.db.dbmodel;

// Generated 30.12.2014 21:24:32 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ergebnis generated by hbm2java
 */
@Entity
@Table(name = "Ergebnis", catalog = "getthepointdb")
public class Ergebnis extends HibernateModel {

	private static final long serialVersionUID = -1090013602142615546L;
	private Integer id;
	private Antwort antwort;
	private Frage frage;
	private Student student;
	private Wissenstest wissenstest;
	private Character richtig;

	public Ergebnis() {
	}

	public Ergebnis(Integer id) {
		this.id = id;
	}

	public Ergebnis(Integer id, Antwort antwort, Frage frage, Student student,
			Wissenstest wissenstest, Character richtig) {
		this.id = id;
		this.antwort = antwort;
		this.frage = frage;
		this.student = student;
		this.wissenstest = wissenstest;
		this.richtig = richtig;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "antwort_id")
	public Antwort getAntwort() {
		return this.antwort;
	}

	public void setAntwort(Antwort antwort) {
		this.antwort = antwort;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "frage_id")
	public Frage getFrage() {
		return this.frage;
	}

	public void setFrage(Frage frage) {
		this.frage = frage;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "student_id")
	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "wissenstest_id")
	public Wissenstest getWissenstest() {
		return this.wissenstest;
	}

	public void setWissenstest(Wissenstest wissenstest) {
		this.wissenstest = wissenstest;
	}

	@Column(name = "richtig", length = 1)
	public Character getRichtig() {
		return this.richtig;
	}

	public void setRichtig(Character richtig) {
		this.richtig = richtig;
	}

}
