package de.hdm.getThePoint.db.dbmodel;

// Generated 30.12.2014 21:24:32 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;

/**
 * Frage generated by hbm2java
 */
@Entity
@Table(name = "Frage", catalog = "getthepointdb")
public class Frage extends HibernateModel {

	private static final long serialVersionUID = -8141793399933091960L;
	private Integer id;
	private Antwort antwort;
	private Kategorie kategorie;
	private String text;
	private Integer schwierigkeit;
	private String bild;
	private Set<ZuordungWissenstestFrage> zuordungWissenstestFrages = new HashSet<ZuordungWissenstestFrage>(
			0);
	private Set<Antwort> antworts = new HashSet<Antwort>(0);
	private Set<Ergebnis> ergebnises = new HashSet<Ergebnis>(0);

	public Frage() {
	}

	public Frage(Integer id, Antwort antwort, Kategorie kategorie) {
		this.id = id;
		this.antwort = antwort;
		this.kategorie = kategorie;
	}

	public Frage(Integer id, Antwort antwort, Kategorie kategorie, String text,
			Integer schwierigkeit, String bild,
			Set<ZuordungWissenstestFrage> zuordungWissenstestFrages,
			Set<Antwort> antworts, Set<Ergebnis> ergebnises) {
		this.id = id;
		this.antwort = antwort;
		this.kategorie = kategorie;
		this.text = text;
		this.schwierigkeit = schwierigkeit;
		this.bild = bild;
		this.zuordungWissenstestFrages = zuordungWissenstestFrages;
		this.antworts = antworts;
		this.ergebnises = ergebnises;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "loesung", nullable = true)
	public Antwort getAntwort() {
		return this.antwort;
	}

	public void setAntwort(Antwort antwort) {
		this.antwort = antwort;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "kategorie_id", nullable = false)
	public Kategorie getKategorie() {
		return this.kategorie;
	}

	public void setKategorie(Kategorie kategorie) {
		this.kategorie = kategorie;
	}

	@Column(name = "text", length = 300)
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	@Column(name = "schwierigkeit")
	public Integer getSchwierigkeit() {
		return this.schwierigkeit;
	}

	public void setSchwierigkeit(Integer schwierigkeit) {
		this.schwierigkeit = schwierigkeit;
	}

	@Column(name = "bild", length = 200)
	public String getBild() {
		return this.bild;
	}

	public void setBild(String bild) {
		this.bild = bild;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "frage")
	public Set<ZuordungWissenstestFrage> getZuordungWissenstestFrages() {
		return this.zuordungWissenstestFrages;
	}

	public void setZuordungWissenstestFrages(
			Set<ZuordungWissenstestFrage> zuordungWissenstestFrages) {
		this.zuordungWissenstestFrages = zuordungWissenstestFrages;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "frage", cascade = CascadeType.ALL)
	@OrderBy("id DESC")
	public Set<Antwort> getAntworts() {
		return this.antworts;
	}

	public void setAntworts(Set<Antwort> antworts) {
		this.antworts = antworts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "frage")
	public Set<Ergebnis> getErgebnises() {
		return this.ergebnises;
	}

	public void setErgebnises(Set<Ergebnis> ergebnises) {
		this.ergebnises = ergebnises;
	}

}
