package de.hdm.getThePoint.db.dbmodel;

// Generated 30.12.2014 21:24:32 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ZuordungWissenstestFrage generated by hbm2java
 */
@Entity
@Table(name = "Zuordung_Wissenstest_Frage", catalog = "getthepointdb")
public class ZuordungWissenstestFrage extends HibernateModel {

	private static final long serialVersionUID = -8472971881473721757L;
	private int id;
	private Frage frage;
	private Wissenstest wissenstest;

	public ZuordungWissenstestFrage() {
	}

	public ZuordungWissenstestFrage(int id) {
		this.id = id;
	}

	public ZuordungWissenstestFrage(int id, Frage frage, Wissenstest wissenstest) {
		this.id = id;
		this.frage = frage;
		this.wissenstest = wissenstest;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "frage_id")
	public Frage getFrage() {
		return this.frage;
	}

	public void setFrage(Frage frage) {
		this.frage = frage;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "wissenstest_id")
	public Wissenstest getWissenstest() {
		return this.wissenstest;
	}

	public void setWissenstest(Wissenstest wissenstest) {
		this.wissenstest = wissenstest;
	}

}
